feat: add support for duckdb_arrow_scan
marcboeker/go-duckdb pull request #283
Opened 2024-09-25 09:54 UTC by fanyang01

This PR exposes the `duckdb_arrow_scan` C API to `go-duckdb` users, partially resolving issue #161.

My use case involves efficiently ingesting Arrow data into DuckDB. Without the feature implemented in this PR, the next best option is to use the `scan_arrow_ipc` function provided by the [DuckDB `arrow` extension](https://github.com/duckdb/arrow), which requires serializing an Arrow table into Arrow IPC buffers.

2024-09-30 11:30 UTC, taniabogatsch requested changes
Hi, @fanyang01. Thanks for the contribution! It looks almost good; I added two comments regarding the error handling and tests.

2024-09-30 11:30 UTC, taniabogatsch commented on arrow.go
> +	}
Let's return `nil, errClosedCon` here, instead of `panic`.

2024-09-30 11:30 UTC, taniabogatsch commented on arrow_test.go
Let's add a test for each error-path. E.g., a closed connection, and some way to trigger `C.DuckDBError`.. maybe an invalid/existing name?

2024-10-02 05:18 UTC, fanyang01 commented
@taniabogatsch Thank you very much for the review! I have added tests for the error paths of duckdb error and closed connection. Other existing `if closed { panic(...) }` patterns have also been changed to `return nil, errClosedCon`.

2024-10-02 10:04 UTC, fanyang01 commented
Sorry for breaking the `register_arrow_stream` test. It should now be working correctly.

```sh
go test -v -run '^TestArrow.*$' .
=== RUN   TestArrow
=== PAUSE TestArrow
=== RUN   TestArrowClosedConn
--- PASS: TestArrowClosedConn (0.01s)
=== CONT  TestArrow
=== RUN   TestArrow/select_series
=== RUN   TestArrow/select_long_series
=== RUN   TestArrow/query_table_and_filter_results
=== RUN   TestArrow/query_error
=== RUN   TestArrow/register_arrow_stream
--- PASS: TestArrow (0.02s)
    --- PASS: TestArrow/select_series (0.00s)
    --- PASS: TestArrow/select_long_series (0.00s)
    --- PASS: TestArrow/query_table_and_filter_results (0.00s)
    --- PASS: TestArrow/query_error (0.00s)
    --- PASS: TestArrow/register_arrow_stream (0.00s)
PASS
ok  	github.com/marcboeker/go-duckdb	1.031s
```

2024-10-02 11:22 UTC, merged

2024-10-02 11:22 UTC, taniabogatsch commented
Thanks!